.gitignore, README.md, mock/AccommodationAPI/apiMetadata.json, mock/FamousAttractionsAPI/apiMetadata.json, mock/HotelAvailabilityAPI/apiMetadata.json, mock/LeisureActivitiesAPI/apiMetadata.json, mock/apiMetadata.json, mock/userProfiles.json, package-lock.json, package.json, src/pages/home/partials/features.hbs, src/pages/tryout/page.hbs, src/partials/footer.hbs
=> Add content for the mock APIS and organization landing page

README.md, package-lock.json, package.json, startup.sh
=> Remove table creation from script

artifacts/script.sql, startup.sh
=> Update startup and SQL scripts

src/layout/main.css, src/pages/apis/partials/api-listing.css, src/pages/apis/partials/api-listing.hbs, src/pages/home/partials/hero.css, src/pages/home/partials/hero.hbs, src/partials/header.hbs
**Add some style changes** 
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable
> Type “Sent” when you have provided new/updated certification questions, plus four answers …
=> Add some style changes 

src/layout/main.css, src/pages/apis/partials/api-listing.css, src/pages/apis/partials/api-listing.hbs, src/pages/apis/partials/pagination.css, src/pages/home/partials/testimonials.css
**Add rating method to listing page**
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact
> Link to the PR for changes to the training content in …
=> Add rating method to listing page

package-lock.json, package.json, src/partials/header.css, src/partials/header.hbs
=> Update user profile

src/pages/apis/partials/api-listing.hbs
=> Display api type in listing page

src/pages/api-landing/partials/api-content.css
=> change some style part

mock/AccommodationAPI/apiMetadata.json, src/layout/main.css, src/pages/api-landing/page.hbs, src/pages/api-landing/partials/api-detail-banner.hbs, src/pages/api-landing/partials/subscription-plans.hbs, src/pages/myAPIs/page.hbs, src/pages/myAPIs/partials/subscribed-api-listing.css, src/pages/myAPIs/partials/subscribed-api-listing.hbs, src/pages/myAPIs/partials/subsribed-api-listing.css, src/pages/myAPIs/partials/subsribed-api-listing.hbs, src/partials/header.hbs
=> Add subscription logic

compress.sh
Modify the compress script to include the organization name
=> Modify compress command

mock/AccommodationAPI/apiMetadata.json, mock/CountriesAPI/apiMetadata.json, mock/LeisureActivitiesAPI/apiMetadata.json, mock/NavigationAPI/apiMetadata.json, mock/apiMetadata.json, src/pages/api-landing/partials/api-detail-banner.hbs, src/pages/apis/partials/api-listing.hbs
Fix issue in API metadata image link
=> Modify api metadata image link

mock/CountriesAPI/apiMetadata.json, mock/LeisureActivitiesAPI/apiMetadata.json, mock/NavigationAPI/apiMetadata.json, mock/apiMetadata.json
=> Fix image links

src/pages/api-landing/partials/api-detail-banner.hbs
=> Fix image link issue

.github/workflows/buid-and-release.yml, config.json
=> Fix the release build

.github/workflows/buid-and-release.yml, config.json
=> Fix workflow and config.json format

mock/Applications/DefaultApplication/AllKeyManagers.json
=> Mock for KM

src/partials/header.hbs
=> Add configure and portal routes

config.json, mock/AccommodationAPI/apiMetadata.json, mock/CountriesAPI/apiMetadata.json, mock/LeisureActivitiesAPI/apiMetadata.json, mock/NavigationAPI/apiMetadata.json, mock/subscriptions.json, package-lock.json, package.json
> Add mock subscriptions for development mode
=> Modify development flow

config.json, mock/IdentityProvider/identityProvider.json, mock/Organization/organizations.json, src/partials/header.hbs
=> Add mock data

package-lock.json, package.json, src/partials/footer.hbs
=> Add style change for footer

mock/APIProviders/APIProviders.json
=> Add mock provider

mock/AccommodationAPI/api-content.hbs, src/pages/apis/partials/api-listing.hbs, src/pages/home/partials/benefits.hbs, src/pages/home/partials/features.hbs, src/pages/home/partials/helpBanner.hbs, src/pages/home/partials/hero.hbs, src/partials/header.hbs
> Fix issues in loading styles and images
=> Fix issues in loading styles and images

src/pages/api-landing/partials/subscription-plans.hbs
=> Fix subscription title display

src/pages/api-landing/partials/api-detail-banner.hbs, src/partials/header.hbs
=> Fix issues in subscription flow
